[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "GoldenViz"
version = "0.0.1"
authors = [
  { name="Wajdi Ben Saad" }
]
description = "do you know the golden rules of a successful data vizulisation? this library helps users to ensure their data viz communicate the information as clearly and neutrally as possible, while respecting a set of Golden Rules."
readme = "README.md"
requires-python = ">=3.8"
