[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "GoldenViz"
version = "0.1.1"
description = "GoldenViz is a Python library that analyzes matplotlib and seaborn charts and checks whether they follow data visualization best practices (the Golden Rules of Data Visualization)."
readme = "README.md"
requires-python = ">=3.10"
license = "AGPL-3.0-or-later"
authors = [
  {name = "Wajdi Ben Saad", email = "wajdi@goldenviz.org"}
]
keywords = [
    "data visualization",
    "matplotlib",
    "seaborn",
    "dataviz",
    "visualization",
    "chart",
    "plot",
    "lint",
    "quality",
    "best practices"
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Visualization",
    "Topic :: Software Development :: Quality Assurance",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent"
]
dependencies = [
    "matplotlib>=3.7",
]

[project.optional-dependencies]
docs = [
    "ipykernel>=6",
    "numpy>=1.23",
    "nbsphinx>=0.9",
    "sphinx>=7",
    "sphinx-rtd-theme>=2",
]
test = [
    "numpy>=1.23",
    "pytest>=8",
]

[project.urls]
Homepage = "https://github.com/WajdiBenSaad/GoldenViz"
Documentation = "https://goldenviz.readthedocs.io"
Repository = "https://github.com/WajdiBenSaad/GoldenViz"
Issues = "https://github.com/WajdiBenSaad/GoldenViz/issues"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
